server:
    port: 8080

logging:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
                
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/training?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: underground
    jpa:
        properties.hibernate:
            enable_lazy_load_no_trans: true
    
keycloak:
    auth-server-url: http://localhost:8081/auth
    realm: stock-manager
    resource: stock-manager
    public-client: true